_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
                - 71
                - 98
                - 100
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
                - 71
                - 98
                - 100
            "3":
                - 2
                - 5
                - 13
                - 14
                - 16
                - 23
                - 55
                - 62
            "4": 3.10.16
            "5": 0.19.10
            "6": 4.51.3
            "8":
                - 5
                - 9
            "10":
                - 20
            "12": 0.19.10
            "13": linux-x86_64
batch_size:
    value: 1
device:
    value: cuda:0
full_run:
    value: false
is_large_model:
    value: false
is_medium_model:
    value: false
limit:
    value: null
model:
    value: EXAONE-3.5-2.4B-Instruct
model_id:
    value: LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct
model_name:
    value: EXAONE-3.5-2.4B-Instruct
num_gpus:
    value: 1
num_tasks:
    value: 10
scheduler_optimized:
    value: false
tasks:
    value:
        - kmmlu
        - kmmlu_hard
        - haerae
        - kobest
        - csatqa
        - kormedmcqa
        - mmlu
        - arc_challenge
        - arc_easy
        - hellaswag
timestamp:
    value: "20250729_183132"
tracking_mode:
    value: baseline
