harness_tasks:
  - kmmlu
  - kmmlu_hard
  - haerae
  - kobest
  - belebele
  - csatqa
  - hrm8k
  - kormedmcqa
  - mmlu
  - mmlu_pro
  - bbh
  - arc_challenge
  - arc_easy
  - hellaswag
  - gsm8k
  - gpqa
  - piqa
  - triviaqa
  - nq_open
  - humaneval
  - agieval
  
custom_tasks:
  - name: "komt_bench"
    module: "tasks.komt_bench"
    few_shot: 0
    input_format: "text_to_text"
  - name: "mt_bench"
    module: "tasks.mt_bench"
    few_shot: 0
    input_format: "text_to_text"
